"""Initial migration

Revision ID: 4204f50bb172
Revises: 
Create Date: 2025-11-23 20:51:33.757655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4204f50bb172'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=28), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('patronymic', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('footer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_counter', sa.Integer(), nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['header_id'], ['header.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'PLN', name='currency'), nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('footer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['footer_id'], ['footer.id'], ),
    sa.ForeignKeyConstraint(['header_id'], ['header.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('footer')
    op.drop_table('header')
    # ### end Alembic commands ###
