"""add enforce to keep only one row of data in readonly_columns table

Revision ID: 444aaa4ca5a3
Revises: de968012f91a
Create Date: 2025-11-29 21:02:33.000225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444aaa4ca5a3'
down_revision: Union[str, Sequence[str], None] = 'de968012f91a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
