"""added column control_sum in Footer Table 

Revision ID: 5b84e965bebf
Revises: 4204f50bb172
Create Date: 2025-11-28 02:38:36.621615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b84e965bebf'
down_revision: Union[str, Sequence[str], None] = '4204f50bb172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('footer', sa.Column('control_sum', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('footer', 'control_sum')
    # ### end Alembic commands ###
